ANCHO_VENTANA  = 800 # Ancho de la pantalla
ALTO_VENTANA    = 600 # Alto de la pantalla
ALTO_PERSONAJE = 20 # Alto del personaje
ANCHO_PERSONAJE = 20 # Ancho del personaje
COLOR_PERSONAJE  = (255, 255, 0) # Color del personaje
COLOR_BG = (0, 0, 20) # Color del fondo
FPS = 60 # Cuadros por segundo
VELOCIDAD = 5 # Velocidad del jugador
SCALA_PERSONAJE = 4   # Escala del personaje
